name: riveo_page_curl
description: Riveo Page Curl

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  flutter_shaders: 0.1.2
  cached_network_image: 3.3.0
  audioplayers: 5.2.0
  flutter_svg: 2.0.8
  flutter_animate: 4.2.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/page_curl.frag
  assets:
    - assets/peel.mp3
